# Generated by Django 5.2.11 on 2026-02-24 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stone", "0005_alter_feedback_options_feedback_image1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crm_type",
                    models.CharField(
                        choices=[
                            ("amo", "AmoCRM"),
                            ("bitrix", "Bitrix24"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("request_data", models.JSONField()),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Stone.feedback",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Stone.countertoporder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог CRM",
                "verbose_name_plural": "Логи CRM",
            },
        ),
    ]
