# Generated by Django 5.2.11 on 2026-02-24 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "Просмотр"),
                            ("click", "Клик"),
                            ("search", "Поиск"),
                            ("order", "Заказ"),
                            ("feedback", "Отзыв"),
                            ("calculation", "Расчет"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("value", models.IntegerField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=500)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Просмотр",
                "verbose_name_plural": "Просмотры",
            },
        ),
    ]
