# Generated by Django 5.2.11 on 2026-02-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stone", "0005_alter_feedback_options_feedback_image1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("order_amount", "Сумма заказа"),
                            ("stone_count", "Количество камней"),
                            ("category", "Категория"),
                            ("first_order", "Первый заказ"),
                            ("birthday", "День рождения"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(help_text="Значение условия", max_length=255),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Приоритет (чем выше, тем важнее)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило скидки",
                "verbose_name_plural": "Правила скидок",
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Промокод"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        default="percent",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Скидка"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальная скидка",
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(default=1, verbose_name="Лимит использований"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Использовано раз"),
                ),
                (
                    "per_user_limit",
                    models.IntegerField(
                        default=1, verbose_name="Лимит на пользователя"
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True,
                        to="Stone.stonecategory",
                        verbose_name="Доступные категории",
                    ),
                ),
                (
                    "applicable_stones",
                    models.ManyToManyField(
                        blank=True, to="Stone.stone", verbose_name="Доступные камни"
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
    ]
