# Generated by Django 5.2.11 on 2026-03-01 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stone", "0006_alter_feedback_options_alter_user_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Вопрос")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Один вариант"),
                            ("multiple", "Несколько вариантов"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=200, verbose_name="Ответ")),
                (
                    "granite_weight",
                    models.IntegerField(default=0, verbose_name="Гранит"),
                ),
                (
                    "marble_weight",
                    models.IntegerField(default=0, verbose_name="Мрамор"),
                ),
                (
                    "quartzite_weight",
                    models.IntegerField(default=0, verbose_name="Кварцит"),
                ),
                (
                    "travertine_weight",
                    models.IntegerField(default=0, verbose_name="Травертин"),
                ),
                ("slate_weight", models.IntegerField(default=0, verbose_name="Сланец")),
                ("onyx_weight", models.IntegerField(default=0, verbose_name="Оникс")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quiz/",
                        verbose_name="Изображение",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="stone_quiz.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("answers", models.JSONField(verbose_name="Ответы")),
                (
                    "granite_score",
                    models.IntegerField(default=0, verbose_name="Гранит"),
                ),
                ("marble_score", models.IntegerField(default=0, verbose_name="Мрамор")),
                (
                    "quartzite_score",
                    models.IntegerField(default=0, verbose_name="Кварцит"),
                ),
                (
                    "travertine_score",
                    models.IntegerField(default=0, verbose_name="Травертин"),
                ),
                ("slate_score", models.IntegerField(default=0, verbose_name="Сланец")),
                ("onyx_score", models.IntegerField(default=0, verbose_name="Оникс")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата прохождения"
                    ),
                ),
                (
                    "recommended_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Stone.stonecategory",
                        verbose_name="Рекомендуемая категория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат теста",
                "verbose_name_plural": "Результаты тестов",
                "ordering": ["-created_at"],
            },
        ),
    ]
