# Generated by Django 5.2.11 on 2026-03-02 10:03

import Stone.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Название камня"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "characteristics",
                    models.TextField(blank=True, verbose_name="Характеристики"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="stones/",
                        validators=[Stone.models.validate_image_size],
                        verbose_name="Главное фото",
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена за м²",
                    ),
                ),
                (
                    "hardness",
                    models.PositiveIntegerField(
                        help_text="По шкале Мооса (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Твердость",
                    ),
                ),
                (
                    "frost_resistance",
                    models.BooleanField(default=True, verbose_name="Морозостойкость"),
                ),
                (
                    "water_absorption",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="В %",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Водопоглощение",
                    ),
                ),
                (
                    "available_finishes",
                    models.CharField(
                        help_text="Через запятую",
                        max_length=200,
                        verbose_name="Доступные обработки",
                    ),
                ),
                (
                    "available_thickness",
                    models.CharField(
                        help_text="Через запятую",
                        max_length=50,
                        verbose_name="Доступные толщины",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="В наличии"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе (м²)"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Популярный"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Новинка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "cutting_price_per_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена резки за м.п.",
                    ),
                ),
                (
                    "edge_processing_prices",
                    models.JSONField(
                        default=dict, verbose_name="Цены на обработку кромки"
                    ),
                ),
                (
                    "sink_cutout_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=3000,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена выреза под мойку",
                    ),
                ),
                (
                    "hob_cutout_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=2500,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена выреза под плиту",
                    ),
                ),
                (
                    "installation_price_per_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=1500,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена монтажа за м.п.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Камень",
                "verbose_name_plural": "Камни",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoneCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        validators=[Stone.models.validate_image_size],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория камня",
                "verbose_name_plural": "Категории камней",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CountertopOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Длина (м)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Ширина (м)",
                    ),
                ),
                (
                    "thickness",
                    models.PositiveIntegerField(
                        choices=[
                            (20, "20 мм"),
                            (30, "30 мм"),
                            (40, "40 мм"),
                            (50, "50 мм"),
                        ],
                        verbose_name="Толщина (мм)",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("straight", "Прямой"),
                            ("rounded", "Закругленный"),
                            ("bevel", "Скос"),
                        ],
                        default="straight",
                        max_length=20,
                        verbose_name="Тип кромки",
                    ),
                ),
                (
                    "sink_type",
                    models.CharField(
                        choices=[
                            ("none", "Без мойки"),
                            ("undermount", "Врезная"),
                            ("integrated", "Интегрированная"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Тип мойки",
                    ),
                ),
                (
                    "cutouts",
                    models.TextField(
                        blank=True,
                        help_text="Описание вырезов под плиту и т.д.",
                        verbose_name="Вырезы",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "customer_phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Телефон"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("customer_address", models.TextField(verbose_name="Адрес")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В обработке"),
                            ("measurement", "Замер"),
                            ("production", "Производство"),
                            ("delivery", "Доставка"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменен"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата заказа"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Итоговая цена",
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Промокод"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Stone.stone",
                        verbose_name="Камень",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ столешницы",
                "verbose_name_plural": "Заказы столешниц",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stone",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stones",
                to="Stone.stonecategory",
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="StoneImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="stones/gallery/",
                        validators=[Stone.models.validate_image_size],
                        verbose_name="Изображение",
                    ),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Stone.stone",
                        verbose_name="Камень",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение камня",
                "verbose_name_plural": "Изображения камней",
                "ordering": ["-is_main", "order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        validators=[Stone.models.validate_image_size],
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="Email-уведомления"),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=False, verbose_name="SMS-уведомления"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "permissions": [
                    ("can_view_analytics", "Может просматривать аналитику")
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_users",
                        to="Stone.stone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("review", "Отзыв"), ("question", "Вопрос")],
                        db_index=True,
                        default="review",
                        max_length=10,
                        verbose_name="Тип обращения",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "numTel",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Номер телефона"
                    ),
                ),
                ("adress", models.TextField(blank=True, verbose_name="Адрес")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 звезда"),
                            (2, "2 звезды"),
                            (3, "3 звезды"),
                            (4, "4 звезды"),
                            (5, "5 звезд"),
                        ],
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "gif", "webp"]
                            ),
                            Stone.models.validate_image_size,
                        ],
                        verbose_name="Фото 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "gif", "webp"]
                            ),
                            Stone.models.validate_image_size,
                        ],
                        verbose_name="Фото 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "gif", "webp"]
                            ),
                            Stone.models.validate_image_size,
                        ],
                        verbose_name="Фото 3",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Подтвержденный заказ"
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "На модерации"),
                            ("approved", "Одобрен"),
                            ("rejected", "Отклонен"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус модерации",
                    ),
                ),
                (
                    "moderation_comment",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Stone.countertoporder",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="Stone.feedback",
                        verbose_name="Ответ на",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "обратная связь",
                "ordering": ["-created_at"],
                "permissions": [("can_moderate_feedback", "Может модерировать отзывы")],
            },
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stones",
                    models.ManyToManyField(
                        related_name="comparisons", to="Stone.stone"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сравнение",
                "verbose_name_plural": "Сравнения",
            },
        ),
        migrations.AddIndex(
            model_name="countertoporder",
            index=models.Index(
                fields=["status", "created_at"], name="Stone_count_status_ec643f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="countertoporder",
            index=models.Index(
                fields=["customer_phone"], name="Stone_count_custome_bb9d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stone",
            index=models.Index(fields=["name"], name="Stone_stone_name_8935c6_idx"),
        ),
        migrations.AddIndex(
            model_name="stone",
            index=models.Index(
                fields=["category", "in_stock"], name="Stone_stone_categor_1bb3b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stone",
            index=models.Index(
                fields=["price_per_sqm"], name="Stone_stone_price_p_ef73fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["user", "added_at"], name="Stone_wishl_user_id_f776b9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "stone")},
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["moderation_status", "is_published"],
                name="Stone_feedb_moderat_954921_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["request_type", "rating"], name="Stone_feedb_request_5ca38f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["user", "created_at"], name="Stone_feedb_user_id_bb8f25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparison",
            index=models.Index(
                fields=["session_key"], name="Stone_compa_session_3706d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparison",
            index=models.Index(fields=["user"], name="Stone_compa_user_id_bb7596_idx"),
        ),
    ]
