# Generated by Django 6.0.2 on 2026-02-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('review', 'Отзыв'), ('question', 'Вопрос')], default='review', max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('numTel', models.CharField(max_length=20)),
                ('adress', models.TextField(blank=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
