# Generated by Django 6.0.2 on 2026-02-18 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'обратная связь'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 18, 18, 53, 0, 8869, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 звезда'), (2, '2 звезда'), (3, '3 звезда'), (4, '4 звезда'), (5, '5 звезда')], null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='adress',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='numTel',
            field=models.CharField(max_length=20, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='request_type',
            field=models.CharField(choices=[('review', 'Отзыв'), ('question', 'Вопрос')], default='review', max_length=10, verbose_name='Тип обращения'),
        ),
    ]
