# Generated by Django 6.0.2 on 2026-02-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stone', '0002_alter_feedback_options_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('numTel', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('adress', models.TextField(blank=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('request_by', models.CharField(choices=[('site', 'Оставить на сайте'), ('call', 'Позвонить')], default='call', max_length=10, verbose_name='Заказать звонок')),
            ],
        ),
    ]
