# Generated by Django 5.2.11 on 2026-03-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Stone", "0002_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countertoporder",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="countertoporder",
            name="promo_code",
        ),
    ]
