# Generated by Django 6.0.2 on 2026-02-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stone', '0003_bymodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokupka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('customer_name', models.CharField(max_length=30, verbose_name='Имя покупателя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'Заказ в обработке'), ('completed', 'Заказ завершен'), ('cancelled', 'Заказ отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('by_models_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokupki', to='Stone.bymodels', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-created_at'],
            },
        ),
    ]
