# Generated by Django 5.2.11 on 2026-02-24 21:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stone", "0004_countertoporder_stone_stonecategory_stoneimage_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "обратная связь",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="reviews/", verbose_name="Фото 1"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="reviews/", verbose_name="Фото 2"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="reviews/", verbose_name="Фото 3"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="Подтвержденный заказ"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="moderation_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий модератора"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "На модерации"),
                    ("approved", "Одобрен"),
                    ("rejected", "Отклонен"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус модерации",
            ),
        ),
        migrations.AddField(
            model_name="stone",
            name="cutting_price_per_m",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                max_digits=10,
                verbose_name="Цена резки за м.п.",
            ),
        ),
        migrations.AddField(
            model_name="stone",
            name="edge_processing_prices",
            field=models.JSONField(
                default=dict, verbose_name="Цены на обработку кромки"
            ),
        ),
        migrations.AddField(
            model_name="stone",
            name="hob_cutout_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2500,
                max_digits=10,
                verbose_name="Цена выреза под плиту",
            ),
        ),
        migrations.AddField(
            model_name="stone",
            name="installation_price_per_m",
            field=models.DecimalField(
                decimal_places=2,
                default=1500,
                max_digits=10,
                verbose_name="Цена монтажа за м.п.",
            ),
        ),
        migrations.AddField(
            model_name="stone",
            name="sink_cutout_price",
            field=models.DecimalField(
                decimal_places=2,
                default=3000,
                max_digits=10,
                verbose_name="Цена выреза под мойку",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="Email-уведомления"),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=False, verbose_name="SMS-уведомления"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stones",
                    models.ManyToManyField(
                        related_name="comparisons", to="Stone.stone"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сравнение",
                "verbose_name_plural": "Сравнения",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_users",
                        to="Stone.stone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["-added_at"],
                "unique_together": {("user", "stone")},
            },
        ),
    ]
