# Generated by Django 6.0.2 on 2026-02-25 07:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stone', '0004_pokupka'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountertopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Длина (м)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина (м)')),
                ('thickness', models.PositiveIntegerField(choices=[(20, '20 мм'), (30, '30 мм'), (40, '40 мм'), (50, '50 мм')], verbose_name='Толщина (мм)')),
                ('edge_type', models.CharField(choices=[('straight', 'Прямой'), ('rounded', 'Закругленный'), ('bevel', 'Скос')], default='straight', max_length=20, verbose_name='Тип кромки')),
                ('sink_type', models.CharField(choices=[('none', 'Без мойки'), ('undermount', 'Врезная'), ('integrated', 'Интегрированная')], default='none', max_length=20, verbose_name='Тип мойки')),
                ('cutouts', models.TextField(blank=True, help_text='Описание вырезов под плиту и т.д.', verbose_name='Вырезы')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('customer_address', models.TextField(verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('measurement', 'Замер'), ('production', 'Производство'), ('delivery', 'Доставка'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заказ столешницы',
                'verbose_name_plural': 'Заказы столешниц',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название камня')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('characteristics', models.TextField(blank=True, verbose_name='Характеристики')),
                ('main_image', models.ImageField(upload_to='stones/', verbose_name='Главное фото')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за м²')),
                ('hardness', models.PositiveIntegerField(help_text='По шкале Мооса (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Твердость')),
                ('frost_resistance', models.BooleanField(default=True, verbose_name='Морозостойкость')),
                ('water_absorption', models.DecimalField(decimal_places=2, help_text='В %', max_digits=5, verbose_name='Водопоглощение')),
                ('available_finishes', models.CharField(help_text='Через запятую', max_length=200, verbose_name='Доступные обработки')),
                ('available_thickness', models.CharField(help_text='Через запятую', max_length=50, verbose_name='Доступные толщины')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе (м²)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория камня',
                'verbose_name_plural': 'Категории камней',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='pokupka',
            name='by_models_order',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='numTel',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stone.countertoporder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='countertoporder',
            name='stone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stone.stone', verbose_name='Камень'),
        ),
        migrations.AddField(
            model_name='stone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='Stone.stonecategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='StoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stones/gallery/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Stone.stone', verbose_name='Камень')),
            ],
            options={
                'verbose_name': 'Изображение камня',
                'verbose_name_plural': 'Изображения камней',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='ByModels',
        ),
        migrations.DeleteModel(
            name='Pokupka',
        ),
    ]
