# Generated by Django 5.2.11 on 2026-02-28 12:30

import Stone.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stone", "0005_alter_feedback_options_feedback_image1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_moderate_feedback", "Может модерировать отзывы")],
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "обратная связь",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_analytics", "Может просматривать аналитику")
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="countertoporder",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Скидка"
            ),
        ),
        migrations.AddField(
            model_name="countertoporder",
            name="promo_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="Промокод"),
        ),
        migrations.AddField(
            model_name="countertoporder",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Итоговая цена",
            ),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="countertoporder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата заказа"
            ),
        ),
        migrations.AlterField(
            model_name="countertoporder",
            name="customer_phone",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="countertoporder",
            name="length",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Длина (м)",
            ),
        ),
        migrations.AlterField(
            model_name="countertoporder",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processing", "В обработке"),
                    ("measurement", "Замер"),
                    ("production", "Производство"),
                    ("delivery", "Доставка"),
                    ("completed", "Выполнен"),
                    ("cancelled", "Отменен"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="countertoporder",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Ширина (м)",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reviews/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    ),
                    Stone.models.validate_image_size,
                ],
                verbose_name="Фото 1",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reviews/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    ),
                    Stone.models.validate_image_size,
                ],
                verbose_name="Фото 2",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reviews/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    ),
                    Stone.models.validate_image_size,
                ],
                verbose_name="Фото 3",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "На модерации"),
                    ("approved", "Одобрен"),
                    ("rejected", "Отклонен"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус модерации",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="numTel",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="request_type",
            field=models.CharField(
                choices=[("review", "Отзыв"), ("question", "Вопрос")],
                db_index=True,
                default="review",
                max_length=10,
                verbose_name="Тип обращения",
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="cutting_price_per_m",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена резки за м.п.",
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="hob_cutout_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2500,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена выреза под плиту",
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="in_stock",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="В наличии"
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="installation_price_per_m",
            field=models.DecimalField(
                decimal_places=2,
                default=1500,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена монтажа за м.п.",
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="is_new",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Новинка"
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="is_popular",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Популярный"
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="main_image",
            field=models.ImageField(
                upload_to="stones/",
                validators=[Stone.models.validate_image_size],
                verbose_name="Главное фото",
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Название камня"
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="price_per_sqm",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена за м²",
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="sink_cutout_price",
            field=models.DecimalField(
                decimal_places=2,
                default=3000,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена выреза под мойку",
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="water_absorption",
            field=models.DecimalField(
                decimal_places=2,
                help_text="В %",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Водопоглощение",
            ),
        ),
        migrations.AlterField(
            model_name="stonecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                validators=[Stone.models.validate_image_size],
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="stoneimage",
            name="image",
            field=models.ImageField(
                upload_to="stones/gallery/",
                validators=[Stone.models.validate_image_size],
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[Stone.models.validate_image_size],
                verbose_name="Аватар",
            ),
        ),
        migrations.AddIndex(
            model_name="comparison",
            index=models.Index(
                fields=["session_key"], name="Stone_compa_session_3706d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comparison",
            index=models.Index(fields=["user"], name="Stone_compa_user_id_bb7596_idx"),
        ),
        migrations.AddIndex(
            model_name="countertoporder",
            index=models.Index(
                fields=["status", "created_at"], name="Stone_count_status_ec643f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="countertoporder",
            index=models.Index(
                fields=["customer_phone"], name="Stone_count_custome_bb9d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["moderation_status", "is_published"],
                name="Stone_feedb_moderat_954921_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["request_type", "rating"], name="Stone_feedb_request_5ca38f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stone",
            index=models.Index(fields=["name"], name="Stone_stone_name_8935c6_idx"),
        ),
        migrations.AddIndex(
            model_name="stone",
            index=models.Index(
                fields=["category", "in_stock"], name="Stone_stone_categor_1bb3b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stone",
            index=models.Index(
                fields=["price_per_sqm"], name="Stone_stone_price_p_ef73fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["user", "added_at"], name="Stone_wishl_user_id_f776b9_idx"
            ),
        ),
    ]
