# Generated by Django 5.2.11 on 2026-02-24 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stone", "0005_alter_feedback_options_feedback_image1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название расчета"),
                ),
                ("length", models.DecimalField(decimal_places=2, max_digits=6)),
                ("width", models.DecimalField(decimal_places=2, max_digits=6)),
                ("thickness", models.IntegerField()),
                ("edge_type", models.CharField(max_length=50)),
                ("has_sink_cutout", models.BooleanField(default=False)),
                ("has_hob_cutout", models.BooleanField(default=False)),
                ("need_installation", models.BooleanField(default=False)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Stone.stone"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохраненный расчет",
                "verbose_name_plural": "Сохраненные расчеты",
                "ordering": ["-created_at"],
            },
        ),
    ]
