# Generated by Django 5.2.11 on 2026-02-24 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stone", "0005_alter_feedback_options_feedback_image1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(verbose_name="Адрес объекта")),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("countertop", "Столешница"),
                            ("window_sill", "Подоконник"),
                            ("stairs", "Ступени"),
                            ("other", "Другое"),
                        ],
                        default="countertop",
                        max_length=50,
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("scheduled", "Запланирован"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Stone.stone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на замер",
                "verbose_name_plural": "Запросы на замер",
            },
        ),
    ]
